### ISSUE TITLE
Bug report: Closing informational overlay removes input data

### ISSUE THREAD

**Issue by roman-mueller** [gchq/CyberChef#1021] opened 2020-04-22 15:29 UTC
**Describe the bug**
When loading data from a file through the "Open file as input" button a informational overlay box gets displayed:
<img width="699" alt="Screen Shot 2020-04-22 at 17 14 03 PM" src="https://user-images.githubusercontent.com/5560575/79999858-ba261f00-84bc-11ea-9ca9-46d27cd06b13.png">

Closing this overlay removes also the input data that was just imported.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Go to https://gchq.github.io/CyberChef/
2. Click on 'Open file as input'
3. Chose any local file, size is not relevant
4. Close the informational overlay by pressing the X in the top right corner
5. Observe the now empty input and output text boxes

**Expected behaviour**
I expected that the loaded input data stays in the input text box after closing the overlay box.

**Desktop (if relevant, please complete the following information):**
 - OS: macOS
 - Browser: Chrome 81
 - CyberChef version: 9.20.3

**Comment by n1474335** [comment] 2020-04-22 15:44
Hi @roman-mueller, this is intended behaviour. We don't actually load the file data fully into the input box since the file could be huge. We display a preview of it behind the file overlay for purely aesthetic reasons, but it is only loaded fully into memory. Input files are not intended to be editable, so therefore closing the file overlay would have no purpose. The close button is there to clear the file from the input.

**Closed by n1474335** 2020-04-22 15:44 UTC
Labels: bug
