### ISSUE TITLE
Bug report: "From Binary" only assumes 8 bit widths

### ISSUE THREAD

**Issue by atoponce** [gchq/CyberChef#907] opened 2019-11-23 15:06 UTC
"From Binary" supports multiple delimiters, but seems to ignore them, and only works on 8-bits. Case in point, binary "0001 1111" should return as "1 15" in decimal, but instead, returns "31".

https://gchq.github.io/CyberChef/#recipe=From_Binary('Space')To_Decimal('Space',false)&input=MDAwMSAxMTEx

Is this expected behavior, or is variable width binary input not supported?

**Comment by NalinGHub** [comment] 2019-11-25 00:56
I think variable width binary is simply not supported right now... when looking at the code for the operation "8+delim.length" is used. I'm sure a variable width binary input could be easily implemented by comparing the length between two successive delimiters and using that length + delim.length if it is less than 8 or 8 if it is greater than 8 (although this may not cover all cases).

**Comment by n1474335** [comment] 2019-11-27 12:42
As @NalinGHub has said, this is intended behaviour rather than a bug. The 'From Binary' operation expects input to be in 8-bit blocks because it is designed to work on a binary stream representing bytes up to 255 in value. If you're looking to convert individual binary numbers, you can use something like this: https://gchq.github.io/CyberChef/#recipe=Fork('%20','%20',false)From_Base(2)&input=MDAwMSAxMTEx
I hope that answers your query. I'll close this for now but if there is additional functionality that you think would be worthwhile adding in, please create a new issue (or feel free to submit a Pull Request).

**Closed by n1474335** 2019-11-27 12:42 UTC

**Comment by atoponce** [comment] 2019-11-27 12:57
Okay. No worries. Thanks for the feedback! Quick question then- what is the delimiter for in the "From Binary" module? How does that behave with hard-coded 8-bit widths?

**Comment by n1474335** [comment] 2019-11-27 16:45
The delimiter is removed before reading in the binary in 8-bit chunks. To be honest, we could get rid of the delimiter parameter altogether and just remove anything that isn't a `1` or a `0`.
