### ISSUE TITLE
Bug report: zip password feature not working

### ISSUE THREAD

**Issue by Belsaros** [gchq/CyberChef#1243] opened 2021-09-14 15:39 UTC
**Describe the bug**
When I use the zip feature:
https://gchq.github.io/CyberChef/#recipe=Zip('malsample.zip','','malwareisbad','Deflate','MSDOS','Dynamic%20Huffman%20Coding') and save the output to a file, I get an incorrect password when I later try to unzip it:
olevba.exe -z malwareisbad malsample.zip
olevba 0.60 on Python 3.7.7 - http://decalage.info/python/oletools
ERROR    Exception opening/reading 'malsample.zip' from zip file 'malsample.zip': Bad password for file 'malsample.zip'

**To Reproduce**
https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)Zip('malsample.zip','','malwareisbad','Deflate','MSDOS','Dynamic%20Huffman%20Coding')&input=VkdocGN5QnBjeUJ6YjIxbElHOTFkSEIxZEFvPQ

1. Go to the above link
2. Click on save output to file
3. Try to unzip file with password used in step 1 "malwareisbad"

**Expected behaviour**
File should unzip properly with provided password

**Desktop (if relevant, please complete the following information):**
 - OS: Windows 10, WSL Ubuntu
 - Browser: Edge Version 93.0.961.44 (Official build) (64-bit)
 - CyberChef version: 9.32.3

**Additional context**

**Comment by mt3571** [comment] 2021-09-14 15:42
Thanks for giving an example of this! This bug is a duplicate of #671

**Comment by mikecat** [comment] 2021-11-18 13:02
This issue looks like due to a bug in zlib.js. (see the duplicate)

**Comment by n1073645** [comment] 2021-11-29 15:24
As this issue is a duplicate, I will close this issue for now.

**Closed by n1073645** 2021-11-29 15:24 UTC
Labels: bug
