### ISSUE TITLE
Bug report:Checkbox not checked on macos safari

### ISSUE THREAD

**Issue by TraderStf** [gchq/CyberChef#492] opened 2019-02-13 09:18 UTC
### Summary
Click on a checkbox, the animation occurs, you see the mark but it disappears, just as if it was not clicked/marked.

**Comment by n1474335** [comment] 2019-02-13 16:39
I can't reproduce this. Are you running any extensions that might be causing this problem?

**Comment by TraderStf** [comment] 2019-02-13 16:46
Setting Safari - Dev - All Extensions OFF, I get this in Safari console:

[Error] TypeError: null is not an object (evaluating 'safari.extension.globalPage')
	postMessage
	sendTo
	send
	onMouseClick
[Error] TypeError: undefined is not an object (evaluating 'safari.self.tab.canLoad')
	shouldBlockDetailedRequest
	(fonction anonyme)
	dispatchEvent
	block (Élément de script 1:1:361)
	onStateChange (Élément de script 1:1:1624)
	replaceState (Élément de script 1:1:1887)
	value (main.js:97:8453)
	value
	dispatchEvent
	value (main.js:115:2945)
	value
	value (main.js:185:10301)
	value

**Comment by n1474335** [comment] 2019-02-13 16:52
I'm not quite sure why the globalPage is being queried. In any case, I'm afraid Safari is not a supported browser. Can you use Chrome or Firefox instead?

**Comment by TraderStf** [comment] 2019-02-13 16:57
Probably not linked, I have domains blocked in /hosts files and modem/mac ports configure to minimum required... that's the fate of sp/cams fighters

Apple, only iOS these days........... testing C and FF

**Comment by TraderStf** [comment] 2019-02-13 16:59
OK in Chrome and FF.

**Comment by n1474335** [comment] 2019-02-15 13:45
Ok, I'll close this as Safari is not a supported browser.

**Closed by n1474335** 2019-02-15 13:45 UTC
