### ISSUE TITLE
saved recipe on timeFormat doesn't load saved format-strings 

### ISSUE THREAD

**Issue by securebyaccident** [gchq/CyberChef#1138] opened 2020-12-02 02:31 UTC
**Describe the bug**
The 'save recipe' functionality is great, but doesn't correctly load saved dateformats for 'translate dateTime Format' 

**To Reproduce**
Steps to reproduce:

1. have input of a unixtime like 1605045122
2. Load/apply 'from Unix Timestamp'
3. Load/apply 'Translate dateTime Format' with 'ddd D MMMM Y HH:mm:ss' as the input format string & 'Y-M-D HH:mm:ss' as the output format string. 
3. use 'Save recipe' with recipe & inputs.
4. load cyberchef again & load your recipe - it does not respect the saved dateFormats / load them, and they're tedious to reconstruct everytime - it's a prime case of why you'd want a saved recipe. 

**Expected behaviour**
Saved recipe's including format-strings in the recipe should be saved & correctly loaded in saved-recipes.  It seems the problem isn't in saving it but loading it correctly. 

**Desktop (if relevant, please complete the following information):**
 - OS: osx 11.01
 - Browser: chrome
 - CyberChef version: v9.21.0

**Additional context**

**Comment by mt3571** [comment] 2020-12-02 16:59
This is a duplication of #1121 for which fix #1136 already exists.

To solve your problem in the meantime, try changing the built in format to `Automatic` and it should load correctly 😀

**Comment by securebyaccident** [comment] 2020-12-03 02:10
Cheers!

**Comment by n1474335** [comment] 2021-09-03 13:48
Duplicate of #1121

**Closed by n1474335** 2021-09-03 13:48 UTC
Labels: bug
