### ISSUE TITLE
Ciphers not loading

### ISSUE THREAD

**Issue by s-dm** [gchq/CyberChef#312] opened 2018-05-26 11:26 UTC
Have downloaded your JS to integrate it into an app, and it works well uncept the ciphers, they are only loading. No output. Tried vigenere, affine and atbash. Rot works.

**Comment by n1474335** [comment] 2018-05-26 12:32
Hi @s-dm, can you give us a bit more information please? When you say "integrate it into an app", what does this mean? If you're importing the JavaScript itself, it might be worth waiting until #291 has been merged into master as this will make things a lot easier for you.

If you're talking about including the web app itself (perhaps in an iframe), it would be useful to know which browser you are using. The CyberChef web app loads some operations (including the cipher operations) separately in modules and this requires a reasonably modern browser that supports web workers and the `importScripts` command.

If I've got the wrong end of the stick, please let me know what the problem is.

**Closed** 2018-08-03 20:30 UTC
