### ISSUE TITLE
Feature request: Please add a Base 91 decoder :)

### ISSUE THREAD

**Issue by 7Ragnarok7** [gchq/CyberChef#1224] opened 2021-07-12 16:01 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by n1474335** [comment] 2021-09-03 16:24
Duplicate of #1213

**Closed by n1474335** 2021-09-03 16:24 UTC
Labels: feature
