### ISSUE TITLE
NEED CRYPTO PADDING OPTIONS

### ISSUE THREAD

**Issue by b1gcat** [gchq/CyberChef#1237] opened 2021-09-03 06:11 UTC
Sometime I see java code :
` Cipher.getInstance("AES/CBC/PKCS5Padding");`

i try use cc to decrypt, but it only support pkcs7padding.

so it's possible to support padding options?

**Comment by n1474335** [comment] 2021-09-03 16:40
Duplicate of #416.

Also, there's no need to shout :)

**Closed by n1474335** 2021-09-03 16:40 UTC
Labels: feature

**Comment by Burgerd4sh** [comment] 2024-09-26 08:05
Now the newest version is v10.19.2
I still can't find PKCS5Padding support, and all issues that mentioned this problem have been closed.
Does anyone know why?
