### ISSUE TITLE
Bug Report: Zlib Inflate / Raw Inflate still reference Compression.js

### ISSUE THREAD

**Issue by into2332** [gchq/CyberChef#341] opened 2018-08-22 20:18 UTC
### Summary

Selecting any of the 'inflate' scripts causes the "Compression Module" loading screen to start and the web console records this message:
`Unhandled promise rejection NetworkError: Failed to load worker script at "https://[[redacted]]/Compression.js" 4e7f70bc-3377-499c-aa25-768cb0a7571c:939:18772`
This file is not emitted by the `grunt prod build` process

**Comment by into2332** [comment] 2018-08-22 20:43
`git clone <CyberChef_URL>`
`cd CyberChef`
`npm install --unsafe-perm`
`grunt prod`

Only half of the files are emitted (WOFF2 files, cyberchef.htm, index.html, images, main.js, sitemap.js, and styles.css).

Executing `grunt prod` a second time produces the additional JS modules.

**Comment by n1474335** [comment] 2018-08-23 21:18
This is caused by the `generateConfig` script not being run correctly. I'm not sure why it's happening for you. I assume it's related to you running as root as discussed in #335.

I'll close this for now but if someone can prove that it's a repeatable problem not caused by running as root, we can reopen it.

**Closed by n1474335** 2018-08-23 21:18 UTC
