### ISSUE TITLE
Bug report: Vertical display is broken

### ISSUE THREAD

**Issue by Unc3nZureD** [gchq/CyberChef#554] opened 2019-05-10 09:54 UTC
### Summary
I'm using a Full HD monitor rotated to vertical position. Input and Output fields are broken and can't be found.

### Debug info
* Version: 8.31.3
* Compile time: 09/05/2019 16:10:55 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true))

### Example
![image](https://user-images.githubusercontent.com/8837736/57518802-3100f100-731a-11e9-9834-7068a274dd65.png)

**Comment by j433866** [comment] 2019-05-28 14:07
Duplicate of #486

**Closed by j433866** 2019-05-28 14:07 UTC
