### ISSUE TITLE
CyberChef_v9.xx - Index page fails to load

### ISSUE THREAD

**Issue by arian-code** [gchq/CyberChef#982] opened 2020-03-15 11:18 UTC
**Describe the bug**
Index page for cyberchef fails to load in Firefox on Windows 2016 or equivalent OS

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Install Firefox 74.0 (64-bit) on Windows 2016 (64-bit)
2. Go to https://gchq.github.io/CyberChef/ (CyberChef_v9.18.0)
3. Page not loading properly:-
   (a) input / output fields not available.
   (b) Script and bake area not proper.
   (c) Functions not available

**Expected behaviour**
The page was expected to load properly

**Screenshots**
1. Screen shot of page not loaded properly.
![bug](https://user-images.githubusercontent.com/43011995/76700317-97117f80-6673-11ea-9a30-da3a49825747.png)

2. Browser console showing errors and warnings.
![browser-consile](https://user-images.githubusercontent.com/43011995/76700319-9d076080-6673-11ea-81bc-388a361f740f.png)

**Desktop (if relevant, please complete the following information):**
 - Windows 2016 or equievlent
 - Firefox 74.0 (64-bit) 
 - https://gchq.github.io/CyberChef/ (CyberChef_v9.18.0 and others) 

**Additional context**
Browser console report:-
03:56:14.602 Unknown category for SetEventRecordingEnabled: fxmonitor
03:56:16.193
Unknown Collection "main/message-groups" RemoteSettingsClient.jsm:146
    UnknownCollectionError resource://services-settings/RemoteSettingsClient.jsm:146
    sync resource://services-settings/RemoteSettingsClient.jsm:379
    InterpretGeneratorResume self-hosted:1157
    AsyncFunctionNext self-hosted:696
03:56:17.112 Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
03:56:17.495
Unknown Collection "main/message-groups" RemoteSettingsClient.jsm:146
    UnknownCollectionError resource://services-settings/RemoteSettingsClient.jsm:146
    sync resource://services-settings/RemoteSettingsClient.jsm:379
    InterpretGeneratorResume self-hosted:1157
    AsyncFunctionNext self-hosted:696
03:56:30.543 NS_ERROR_FAILURE: data:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLQogICAgVHVyaW5nLVdlbGNobWFuIEJvbWJlIFN:23
03:56:31.482 Request to access cookie or storage on “https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=…_gid=1556541333.1584208868&gjid=1393272340&_v=j81&z=97616543” was blocked because it came from a tracker and content blocking is enabled.

**Comment by d98762625** [comment] 2020-05-28 08:57
Hi @arian-code, I cannot attempt to recreate this bug as I have a different environment.

A quick google tells me that the fxmonitor is a firefox project and so I suspect that this is an issue with the version of firefox you're running. Could you update your Firefox version and try again?

**Comment by arian-code** [comment] 2020-05-28 09:00
The problem persist even in Chrome. Only way I found to bypass is decrease window frame

**Comment by n1474335** [comment] 2021-09-03 13:26
Duplicate of #486

**Closed by n1474335** 2021-09-03 13:26 UTC
Labels: bug
