### ISSUE TITLE
Bug report: Regular expression wiped when loading a recipe

### ISSUE THREAD

**Issue by lasq88** [gchq/CyberChef#563] opened 2019-05-21 07:05 UTC
Everytime I am loading a recipe (no matter if from local storage or json, or cyberchef format) all included regular expressions get wiped. So instead of a regular expression I created there is an empty field and I have to recreate an expression.

**Comment by j433866** [comment] 2019-05-21 15:50
Duplicate of #532

**Closed by j433866** 2019-05-21 15:50 UTC
