### ISSUE TITLE
Bug report: Loaded Regex recipe has an empty pattern if it contained a forward slash

### ISSUE THREAD

**Issue by ilyaglow** [gchq/CyberChef#555] opened 2019-05-12 13:53 UTC
### Summary
The loaded regex recipe has an empty pattern field if it contained a forward slash.
Looks similar to #319.

### Example
https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','b/',true,true,false,false,false,false,'List%20matches')&input=YQplLwpiLwovZA

**Comment by j433866** [comment] 2019-05-16 10:40
Duplicate of #532

**Closed by j433866** 2019-05-16 10:40 UTC
