### ISSUE TITLE
Feature request: add padding option to block ciphers

### ISSUE THREAD

**Issue by NyaMisty** [gchq/CyberChef#574] opened 2019-06-11 17:24 UTC
### Summary
The DES and AES are using PKCS#7 padding all the time, even if the original data is not padded. That's causing ```Unable to decrypt input with these parameters.``` in the CyberChef.
We can add a new option for user to specify the padding method.

**Comment by j433866** [comment] 2019-06-12 10:14
Duplicate of #416

**Closed by j433866** 2019-06-12 10:14 UTC

**Comment by NyaMisty** [comment] 2019-06-12 10:17
Sorry I forgot to search first. I apologize 😣
