### ISSUE TITLE
Bug report: npm install --save cyberchef failled

### ISSUE THREAD

**Issue by QKSword** [gchq/CyberChef#1227] opened 2021-07-31 04:05 UTC
**I want to use Node API，but ”npm install --save cyberchef“ face the problem**

`npm ERR! cyberchef@9.27.6 postinstall: npx grunt exec:fixCryptoApiImports`
`npm ERR! Exit status 3`

environment：System：ubutun:20.04.2；nodejs：v10.19.0；npm：6.14.4

**Comment by n1474335** [comment] 2021-09-03 16:26
Duplicate of #1166

**Closed by n1474335** 2021-09-03 16:26 UTC
Labels: bug
